name: Deploy RMarkdown to Posit Connect

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PR to main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on Ubuntu Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'  # Specify the R version you are using

      - name: Install dependencies
        run: |
          R -e "install.packages(c('remotes', 'rmarkdown'))"
          R -e "remotes::install_github('rstudio/connectapi')"

      - name: Render the RMarkdown file
        run: |
          Rscript -e "rmarkdown::render('your_file.Rmd')"  # Replace with the actual file name

      - name: Deploy to Posit Connect
        run: |
          curl -X POST \
            -F "content=@your_file.html" \
            -F "name=your_file" \
            -F "publish=TRUE" \
            -H "Authorization: Bearer ${{ secrets.POSIT_CONNECT_TOKEN }}" \
            https://connect.posit.cloud/__api__/v1/assets  # Change the URL if needed

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass GitHub token as an environment variable
          POSIT_CONNECT_TOKEN: ${{ secrets.POSIT_CONNECT_TOKEN }}  # GitHub secret for Posit Connect Token
